networks:
  mysql:
  common:

x-prism-base: &prism-base
  build: .
  volumes:
    - .:/app
    - ./docker/scripts:/scripts
    - ./docker/bootstrap:/bootstrap
    - prism-bundle:/app/vendor/bundle
    - prism-tmp:/app/tmp
  env_file:
    - ./docker/env
  networks:
    - common
  depends_on:
    - mysql
    - redis

services:
  mysql:
    image: mysql:8.0.33
    command: --character-set-server=utf8mb3 --collation-server=utf8mb3_unicode_ci
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: joshua
    ports:
      - "${PORTS-}3307:3306"
    volumes:
      - ./docker/mysql/data:/data
      - mysql-data:/var/lib/mysql:delegated
    networks:
      - common
  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy
  #   ports:
  #     - "${PORTS-}080:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - nginx-proxy-certs:/etc/nginx/certs
  #     - ./services/nginx-proxy/etc/proxy.conf:/etc/nginx/proxy.conf
  #   networks:
  #     - common
  prism-puma:
    <<: *prism-base
    ports:
      - "${PORTS-}7339:9292"
    environment:
      RAILS_DEVELOPMENT_HOSTS: "prism.evdev.eu,prism-puma"
      RAILS_ENV: development
      VIRTUAL_HOST: "prism.evdev.eu,everum-en.evdev.eu,everum-ru.evdev.eu,everum.evdev.eu,vibe-en.evdev.eu,vibe-ru.evdev.eu,vibe.evdev.eu"
      VIRTUAL_PATH: "/prism_engine"
      VIRTUAL_PORT: "9292"
      PROMETHEUS_EXPORTER_PORT: "8888"
      YABEDA_SIDEKIQ_COLLECT_CLUSTER_METRICS: "yes"
      WAIT_HOSTS: mysql:3306
      WAIT_TIMEOUT: 1800
    command: sh -c '/scripts/wait && /bootstrap/bootstrap.sh && bundle exec puma -b tcp://0.0.0.0:9292 -v'
  prism-sidekiq:
    <<: *prism-base
    environment:
      RAILS_ENV: development
      PROMETHEUS_EXPORTER_PORT: "8888"
      YABEDA_SIDEKIQ_COLLECT_CLUSTER_METRICS: "no"
      WAIT_HOSTS: prism-puma:9292
      WAIT_TIMEOUT: 1800
    command: sh -c '/scripts/wait && bundle exec sidekiq -c 1 -v'
  prism-test:
    <<: *prism-base
    environment:
      RAILS_ENV: test
      RACK_ENV: test
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: "mysql2://root:joshua@mysql/prism_test?pool=25"
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      WAIT_HOSTS: prism-puma:9292
      WAIT_TIMEOUT: 1800
    command: sh -c '/scripts/wait && rm -rf /tmp/spring* && bundle exec spring server'
  redis:
    image: redis:latest
    ports:
      - "${PORTS-}6379:6379"
    networks:
      - common
  bootstrap:
    <<: *prism-base
    environment:
      RAILS_ENV: development
      READY_PORT: 1334
    ports:
      - 1334
    command: sh -c './docker/scripts/wait-for-it.sh mysql:3306 -t 0 -- ./docker/scripts/bootstrap.sh'

volumes:
  common:
  mysql-data:
  nginx-proxy-certs:
  prism-bundle:
  prism-tmp:
  rails-bundle:
  rails-tmp:
